server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: yu-ai-agent
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  datasource:
    mysql:
      url: jdbc:mysql://192.168.10.5:3306/yu_ai_agent?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgresql:
      url: jdbc:postgresql://192.168.10.5:5432/yu_ai_agent
      username: root
      password: 1234
      driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # 设置单个文件的最大大小
      max-request-size: 10MB    # 设置整个请求的最大大小

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:14b
        #model: deepseek-r1:32b #32b模型会超时！
        #model: gemma3:12b #rag提示词是英文的，会导致用户输入中文，Ai回复英文
      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 768 #默认为1536，但是nomic-embed-text是768
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

    mcp:
      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json

        sse:
          connections:
            server1:
              url: http://localhost:8127
        # stdio:
        # servers-configuration: classpath:mcp-servers.json



chat:
  memory:
    type: file  # 可以设置为 "mysql", "file", 或 "memory"

mybatis:
  # 这个位置是 MyBatis 映射文件的路径，确保 XML 文件位置正确
  mapper-locations: classpath:mapper/*.xml
  # 设置 MyBatis 映射的类路径（简化 Mapper 接口的使用）
  type-aliases-package: com.yupi.yuaiagent.domain.dto

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
